version: '3'

services:
 web:
    build: ./docker_nginx
    ports:
        - 80:80
        - 443:443
    depends_on:
        - app
    volumes:
        - ./src:/var/www/html
        - ./docker_nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - app
 app:
    build: ./docker_php
    # depends_on:
    #     - db
    # links:
    #     - db
    volumes:
        - ./src:/var/www/html
 # db:
 #    image: mysql:5.7.19
 #    ports:
 #      - 3306:3306
 #    environment:
 #      MYSQL_ROOT_PASSWORD: root         #ここにroot用のパスワードを記載
 #      MYSQL_DATABASE: test_db           #ここにデータベースを記載
 #      MYSQL_USER: test_user             #ここにユーザ名を記載
 #      MYSQL_PASSWORD: test              #ここにユーザ用パスワードを記載